services:
  web:
    build: ./project
    command: >
       bash -c "alembic revision --autogenerate && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./project/:/usr/src/app/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:8000
      - 5555:5555
    tty: true
    env_file:
      - ./project/.env.dev
    depends_on:
      redis:
        condition: service_started
    container_name: test_Unistream

  redis:
    image: redis:6.2
